FROM centos

MAINTAINER Shiva Chaitanya Madduru <smadduru@hawk.iit.edu>


# Install Mariadb

RUN yum install mariadb-server mariadb



# Opening Port 3306 for mariadb
EXPOSE 3306


#Run/Start Mariadb
ENTRYPOINT ["mariadb"]



