FROM ubuntu

MAINTAINER Shiva Chaitanya Madduru <smadduru@hawk.iit.edu>


# Install Mariadb

RUN apt-get install mariadb-server 



# Opening Port 3306 for mariadb
EXPOSE 3306


#Run/Start Mariadb
ENTRYPOINT ["/usr/sbin/mysqld"]



