FROM centos

MAINTAINER Shiva Chaitanya Madduru <smadduru@hawk.iit.edu>


# Install Web Server, PhpModules and SSL

RUN yum install httpd
RUN yum install php php-common php-mysql php-pdo php-gd php-mbstring
RUN yum install mod_ssl


# Opening Ports 80 and 443 for http
EXPOSE 80
EXPOSE 443

#Copy info.php
COPY info.php /var/www/html/info.php



#Run/Start Apache

ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]



