FROM centos

MAINTAINER Shiva Chaitanya Madduru <smadduru@hawk.iit.edu>

# Making Volume available to other containers

VOLUME /data/mariadb

# Keeping the container open

ENTRYPOINT ["bash"]
